### PR TITLE
Solved the screen tearing issue with nvidia gpu devices

### PR DESCRIPTION
**Pull request by AndroX2**
*Tested with 'nvidia GTX 850M'
`glx` and `xr_glx_hybrid` both works

### CODE REVIEW

**Comment by arcolinuxz** [comment]
your solution might not be a solution for the whole wide world.
you better put this knowledge you now posess on https://arcolinuxforum.com together with a inxi -b and a probe link
so that users with your hardware are helped 
closing here

**Comment by AndroX2** [comment]
It can be be a solution for everyone too. Also I think xr_glx_hybrid will give more flexibility over xrender. So, I request you to do some test on different real machine before reaching to conclusion.

**Comment by arcolinuxz** [comment]
please put it on the forum
not everyone has nvidia

**Comment by arcolinuxz** [comment]
https://youtu.be/b3WbZM_6tBc

**Comment by arcolinuxz** [comment]
https://arcolinuxforum.com/viewtopic.php?f=80&t=2802&p=11363#p11363

**Comment by AndroX2** [comment]
Ok thanks for the information

**Pull request closed without merging**
